# Generated by Django 5.0.6 on 2024-07-03 17:55

import django.db.models.deletion
import django.utils.timezone
import phac_aspc.django.fields
import versionator.core
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "name_fr",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "name_fr",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "code",
                    phac_aspc.django.fields.CharField(
                        max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "name_fr",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "business_key",
                    phac_aspc.django.fields.CharField(
                        max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    phac_aspc.django.fields.CharField(
                        default="active", max_length=50
                    ),
                ),
                (
                    "tags",
                    phac_aspc.django.fields.ManyToManyField(
                        to="my_app.projecttag"
                    ),
                ),
                (
                    "project_type",
                    phac_aspc.django.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.projecttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTagHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name_en", phac_aspc.django.fields.CharField(max_length=255)),
                ("name_fr", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttag",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "name_fr",
                    phac_aspc.django.fields.CharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "project",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name_en", phac_aspc.django.fields.CharField(max_length=255)),
                ("name_fr", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttask",
                    ),
                ),
                (
                    "project",
                    phac_aspc.django.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name_en", phac_aspc.django.fields.CharField(max_length=255)),
                ("name_fr", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "business_key",
                    phac_aspc.django.fields.CharField(max_length=50),
                ),
                (
                    "status",
                    phac_aspc.django.fields.CharField(
                        default="active", max_length=50
                    ),
                ),
                ("tags", versionator.core.M2MTextField(default="[]")),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.project",
                    ),
                ),
                (
                    "project_type",
                    phac_aspc.django.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_app.projecttype",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTypeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name_en", phac_aspc.django.fields.CharField(max_length=255)),
                ("name_fr", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "description_en",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                (
                    "description_fr",
                    phac_aspc.django.fields.TextField(default=""),
                ),
                ("code", phac_aspc.django.fields.CharField(max_length=100)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttype",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", phac_aspc.django.fields.CharField(max_length=50)),
                (
                    "project",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.project",
                    ),
                ),
                (
                    "user",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
