# Generated by Django 4.1.9 on 2023-06-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_app.models.model_util
import proj.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_key",
                    proj.fields.CharField(max_length=50, unique=True),
                ),
                (
                    "status",
                    proj.fields.CharField(default="active", max_length=50),
                ),
            ],
            options={
                "abstract": True,
            },
            bases=(
                models.Model,
                my_app.models.model_util.BilingualDescriptionMixin,
                my_app.models.model_util.BilingualNameMixin,
            ),
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": True,
            },
            bases=(
                models.Model,
                my_app.models.model_util.BilingualNameMixin,
                my_app.models.model_util.BilingualDescriptionMixin,
            ),
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    proj.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.project",
                    ),
                ),
            ],
            options={
                "abstract": True,
            },
            bases=(
                models.Model,
                my_app.models.model_util.BilingualDescriptionMixin,
                my_app.models.model_util.BilingualNameMixin,
            ),
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", proj.fields.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": True,
            },
            bases=(
                models.Model,
                my_app.models.model_util.BilingualDescriptionMixin,
                my_app.models.model_util.BilingualNameMixin,
            ),
        ),
        migrations.CreateModel(
            name="ProjectUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", proj.fields.CharField(max_length=50)),
                (
                    "project",
                    proj.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.project",
                    ),
                ),
                (
                    "user",
                    proj.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTypeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("code", proj.fields.CharField(max_length=100)),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttype",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttask",
                    ),
                ),
                (
                    "project",
                    proj.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTagHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.projecttag",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("business_key", proj.fields.CharField(max_length=50)),
                (
                    "status",
                    proj.fields.CharField(default="active", max_length=50),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
    ]
